import os
import json
import random
import csv

def build_env():
    # Fixed seed for deterministic evaluation
    random.seed(1314)
    
    # Create directories
    os.makedirs("appointments", exist_ok=True)
    for i in range(1, 5):
        os.makedirs(f"appointments/week_{i}", exist_ok=True)
    os.makedirs("payment_gateway", exist_ok=True)
    os.makedirs("expenses", exist_ok=True)
    os.makedirs("finance_summary", exist_ok=True)

    stylists = ['R-88', 'L-22', 'M-11']
    clients = [
        "Maria V.", "Elena", "Lucia", "Mrs. Smith", "Carmen", "Sofia", 
        "Juan", "Isabella", "Diego", "Valeria", "Carlos", "Camila"
    ]
    
    appointments_data = []
    
    # 1. Generate Appointments (Wasteland style: scattered, some cancelled, some corrupted)
    for i in range(1, 601):
        app_id = f"APP_{1000 + i}"
        stylist = random.choice(stylists)
        client = random.choice(clients) + f"_{i}" # Unique names for tracking
        price = round(random.uniform(15.0, 150.0), 2)
        cancelled = random.random() < 0.15
        
        # Decide payment status early to build gateway logs
        status = random.choice(["SUCCESS", "SUCCESS", "SUCCESS", "PENDING", "FAILED"])
        
        record = {
            "id": app_id,
            "stylist": stylist,
            "client": client,
            "service_cost": price,
            "cancelled": cancelled
        }
        appointments_data.append((record, status))
        
        week_folder = f"appointments/week_{random.randint(1, 4)}"
        file_path = os.path.join(week_folder, f"{app_id}.json")
        
        # Introduce a few corrupted files (noise/wasteland element)
        if random.random() < 0.02:
            with open(file_path, "w", encoding="utf-8") as f:
                f.write('{"id": "' + app_id + '", "stylist": "R-88", \n\n BROKEN FILE \n')
        else:
            with open(file_path, "w", encoding="utf-8") as f:
                json.dump(record, f, indent=2)

    # 2. Generate Payment Gateway Logs (Noise + Multi-hop)
    log_files = [open(os.path.join("payment_gateway", f"gateway_node_{i}.log"), "w", encoding="utf-8") for i in range(1, 4)]
    
    for record, status in appointments_data:
        log_f = random.choice(log_files)
        app_id = record["id"]
        
        # Noise lines
        if random.random() < 0.3:
            log_f.write(f"[DEBUG] 2023-11-XX - Initializing payment stream for {app_id}...\n")
        if random.random() < 0.2:
            log_f.write(f"[WARN] 2023-11-XX - Network jitter detected for {app_id}, retrying...\n")
            
        # The true status line
        log_f.write(f"[INFO] Payment confirmed for {app_id}: {status}\n")

    for log_f in log_files:
        log_f.close()

    # 3. Generate Dirty Expenses TSV
    expenses_file = os.path.join("expenses", "expenses_dump.tsv")
    categories = ["BUSINESS", "PERSONAL", "ERROR"]
    
    with open(expenses_file, "w", encoding="utf-8") as f:
        f.write("TXN_DATE\tDETAILS\tCAT\tAMOUNT_USD\n")
        f.write("# SYSTEM EXPORT GENERATED BY NEPHEW_APP v0.1\n") # Noise header
        
        for i in range(300):
            cat = random.choice(categories)
            base_amount = round(random.uniform(5.0, 80.0), 2)
            
            # Dirty money formats
            fmt_choice = random.randint(1, 4)
            if fmt_choice == 1:
                dirty_amount = f"${base_amount}"
            elif fmt_choice == 2:
                dirty_amount = f"{base_amount} USD"
            elif fmt_choice == 3:
                dirty_amount = f" {base_amount} "
            else:
                dirty_amount = str(base_amount)
                
            details = f"Store_Purchase_{i}"
            f.write(f"2023-11-{random.randint(1, 30):02d}\t{details}\t{cat}\t{dirty_amount}\n")

if __name__ == "__main__":
    build_env()
