import os
import sys
import base64
import httpx
from openai import OpenAI

# Strict mock API standards
MOCK_API_KEY = os.environ.get("MOCK_API_KEY", "dummy_key")
MOCK_API_BASE = os.environ.get("MOCK_API_BASE", "http://localhost/v1")
MOCK_MODEL_NAME = os.environ.get("MOCK_MODEL_NAME", "gpt-5.4")

def execute(node_id: str, query: str) -> str:
    """
    LLM-as-a-Mock tool to decode proprietary binary logs, filter noise, 
    and provide intelligent insights based on the SRE's query.
    """
    if not node_id or not query:
        return "Error: Missing required parameters. 'node_id' and 'query' must be provided."
    
    file_path = os.path.join("cluster_logs", f"{node_id}.pcap_raft")
    
    if not os.path.exists(file_path):
        return f"System Error: Cannot find binary capture file for node '{node_id}' at {file_path}."
        
    try:
        # 1. Decode the proprietary format locally
        with open(file_path, "rb") as f:
            data = f.read()
            
        if not data.startswith(b"RAFT_PCAP_V2"):
            return "Format Error: Magic header missing. The file might be corrupted."
            
        encoded_payload = data[12:]
        decoded_text = base64.b64decode(encoded_payload).decode("utf-8")
        
        # 2. Extract meaningful Raft lifecycle and RPC events to avoid LLM context overflow
        # Discarding heavy memory and CPU trace garbage generated by env_builder
        filtered_lines = []
        for line in decoded_text.split("\n"):
            if any(noise in line for noise in ["DEBUG_DUMP", "TRACE_TICK", "MEM_SWEEP"]):
                continue
            if "||" in line:
                filtered_lines.append(line)
                
        if not filtered_lines:
            return f"AIOps Analysis: No meaningful Raft consensus events found in the log of {node_id}."
            
        # Limit lines just in case
        log_snippet = "\n".join(filtered_lines[-100:]) 
        
        # 3. Call the Mock LLM API
        http_client = httpx.Client(verify=False)
        client = OpenAI(
            api_key=MOCK_API_KEY,
            base_url=MOCK_API_BASE,
            http_client=http_client
        )
        
        system_prompt = (
            "You are an SRE Copilot diagnostic AI. You are provided with a sequence of filtered Raft RPC logs "
            "from a specific node. Parse the logs accurately and answer the user's query. If you see terms like "
            "conflictTerm, conflictIdx, my_idx, my_t, point them out clearly."
        )
        
        user_prompt = f"Target Node: {node_id}\nFiltered Log Snippet:\n{log_snippet}\n\nUser Query: {query}"
        
        response = client.chat.completions.create(
            model=MOCK_MODEL_NAME,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ],
            temperature=0.1
        )
        
        return response.choices[0].message.content
        
    except Exception as e:
        return f"AIOps Backend Error: Failed to analyze node log. Exception: {str(e)}"
