import argparse
import sys

def main():
    parser = argparse.ArgumentParser(description="Fast legacy AST binary parser")
    parser.add_argument("--file", required=True, help="Path to the .astbin file")
    args = parser.parse_args()
    
    print(f"[Info] Loading AST binary symbols from {args.file}...")
    print("[Fatal Error] Version mismatch: The AST binary was generated by Clang-16, but this fast parser only supports up to Clang-12.")
    print("Segmentation fault (core dumped).")
    print("Hint: Please switch to the advanced tool: llvm_ast_oracle_skill.py")
    sys.exit(1)

if __name__ == "__main__":
    main()
