import os
import json
import csv
import random
import uuid

def build_env():
    # Set a fixed seed for reproducibility
    random.seed(1717)
    
    # Target active device IDs
    active_solar = ["SOL-A11", "SOL-B22"]
    active_water = ["WAT-777", "WAT-888"]
    
    # Noise IDs
    noise_solar = ["SOL-OLD", "NGHBR-SOL-99", "SOL-BROKEN"]
    noise_water = ["WAT-OLD", "NGHBR-WAT-12"]

    # 1. Create the Documents folder with the multi-hop clue
    os.makedirs("documents", exist_ok=True)
    installer_note = """Dear Mrs. Higgins,
Thank you for your purchase! Your new eco-system is now up and running.
Please note that your hub might still pick up signals from your old devices, 
as well as the neighbor's unencrypted network. 

For your records, your ACTIVE device serial numbers are:
Solar Panels: SOL-A11, SOL-B22
Water Monitors: WAT-777, WAT-888

Please ignore any data from other serial numbers.
Best,
Frank the Installer
"""
    with open("documents/installer_note.txt", "w") as f:
        f.write(installer_note)

    # 2. Create the sprawling, fragmented gadget_dumps directory
    os.makedirs("gadget_dumps", exist_ok=True)
    
    total_solar_kwh = 0
    total_water_gallons = 0

    # Generate 100 sync sessions to simulate scale
    for session_id in range(1, 101):
        session_dir = f"gadget_dumps/sync_session_{session_id:03d}"
        os.makedirs(session_dir, exist_ok=True)
        
        # Each session has 3-7 random files
        num_files = random.randint(3, 7)
        for i in range(num_files):
            file_type = random.choices(
                ["valid_solar", "valid_water", "noise_solar", "noise_water", "receipt", "random_log"],
                weights=[20, 20, 15, 15, 10, 20],
                k=1
            )[0]
            
            # Generate obfuscated filename
            file_hash = str(uuid.uuid4())[:8]
            
            if file_type in ["valid_solar", "noise_solar"]:
                # Solar logs are CSVs
                filename = os.path.join(session_dir, f"energy_sync_{file_hash}.csv")
                device_id = random.choice(active_solar) if file_type == "valid_solar" else random.choice(noise_solar)
                kwh = random.randint(5, 25)
                
                if file_type == "valid_solar":
                    total_solar_kwh += kwh
                    
                with open(filename, "w", newline="") as f:
                    writer = csv.writer(f)
                    writer.writerow(["timestamp", "device_id", "energy_kwh"])
                    writer.writerow([f"2023-10-{random.randint(1,28):02d}T12:00:00Z", device_id, kwh])
                    
            elif file_type in ["valid_water", "noise_water"]:
                # Water logs are JSONs
                filename = os.path.join(session_dir, f"flow_metrics_{file_hash}.json")
                device_id = random.choice(active_water) if file_type == "valid_water" else random.choice(noise_water)
                gallons = random.randint(10, 50)
                
                if file_type == "valid_water":
                    total_water_gallons += gallons
                    
                with open(filename, "w") as f:
                    json.dump({
                        "sync_meta": {"protocol": "zigbee", "rssi": -65},
                        "payload": {
                            "device_id": device_id,
                            "gallons_saved": gallons
                        }
                    }, f)
                    
            elif file_type == "receipt":
                # Pure noise text file
                filename = os.path.join(session_dir, f"scan_{file_hash}.txt")
                with open(filename, "w") as f:
                    f.write("Grocery Mart\nApples: $2.99\nOat Milk: $4.50\nTotal: $7.49\nHave a nice day!")
                    
            elif file_type == "random_log":
                # Fake system logs
                filename = os.path.join(session_dir, f"sys_debug_{file_hash}.log")
                with open(filename, "w") as f:
                    f.write(f"[WARN] Failed to handshake with node {random.randint(100, 999)}\n[INFO] Battery level OK.")

    # Note: I am NOT printing the totals to stdout to prevent the Agent from cheating by reading the env_builder.py output.
    # The true totals for validation purposes will be deterministically generated by the random seed.

if __name__ == "__main__":
    build_env()
