import os
import json
import re
import sys

def check_density(content, art_id, expected_val):
    # Matches the artifact ID followed by non-alphanumeric separators, then a float
    pattern1 = f"{art_id}[^0-9a-zA-Z]+([0-9]+\\.?[0-9]*)"
    match1 = re.search(pattern1, content)
    if match1 and abs(float(match1.group(1)) - expected_val) < 0.05:
        return True

    # Matches a float followed by non-alphanumeric separators, then the artifact ID
    pattern2 = f"([0-9]+\\.?[0-9]*)[^0-9a-zA-Z]+{art_id}"
    match2 = re.search(pattern2, content)
    if match2 and abs(float(match2.group(1)) - expected_val) < 0.05:
        return True

    return False

def verify():
    state = {
        "has_submission_folder": False,
        "has_output_file": False,
        "filtered_unregistered_artifacts": False,
        "filtered_corrupted_data": False,
        "correct_avg_densities": False
    }

    if os.path.exists("grant_submission") and os.path.isdir("grant_submission"):
        state["has_submission_folder"] = True
        
        files = os.listdir("grant_submission")
        if len(files) > 0:
            state["has_output_file"] = True
            
            # Read the first file generated by the agent
            out_file_path = os.path.join("grant_submission", files[0])
            try:
                with open(out_file_path, "r", encoding="utf-8") as f:
                    content = f.read()
                    
                # 1. Check if unregistered artifacts were correctly filtered out
                if "ART-003" not in content and "ART-011" not in content:
                    state["filtered_unregistered_artifacts"] = True
                    
                # 2. Check if corrupted data was ignored (ART-004 should average to 4.0, not negative)
                # If negative data was included, the average would be much lower/negative.
                if check_density(content, "ART-004", 4.0):
                    state["filtered_corrupted_data"] = True
                    
                # 3. Check correct mathematical densities for the rest
                art1_correct = check_density(content, "ART-001", 5.0)
                art2_correct = check_density(content, "ART-002", 5.0)
                art7_correct = check_density(content, "ART-007", 4.0)
                
                if art1_correct and art2_correct and art7_correct:
                    state["correct_avg_densities"] = True
                    
            except Exception as e:
                pass

    with open("state.json", "w") as f:
        json.dump(state, f, indent=4)

if __name__ == "__main__":
    verify()
