import os
import json
import yaml
import random
import hashlib
from datetime import datetime, timedelta

def build_env():
    # Set a fixed seed for reproducible chaos
    random.seed(1657)
    
    # Define directories
    dirs = [
        "metadata",
        "logs/quality_control",
        "finance/invoices",
        "audio_archive",
        "ready_for_mix"
    ]
    for d in dirs:
        os.makedirs(d, exist_ok=True)

    total_sessions = 350
    sessions = []
    
    # 1. Generate Session Registry
    for i in range(1, total_sessions + 1):
        sessions.append({
            "session_id": f"SES-{i:03d}",
            "track_name": f"Track_{random.choice(['Alpha', 'Beta', 'Gamma', 'Delta', 'Echo', 'Void'])}",
            "engineer": random.choice(["Dave", "Sarah", "Mike", "Elena", "BOT_AUTO"])
        })
    
    with open("metadata/session_registry.json", "w") as f:
        json.dump({"total": total_sessions, "sessions": sessions}, f, indent=4)

    # 2. Generate QC Logs (Fragmented across date folders with noise)
    start_date = datetime(2023, 1, 1)
    for session in sessions:
        # Create deep date-based folders
        day_offset = random.randint(0, 180)
        current_date = start_date + timedelta(days=day_offset)
        date_path = os.path.join(
            "logs/quality_control", 
            str(current_date.year), 
            f"{current_date.month:02d}", 
            f"{current_date.day:02d}"
        )
        os.makedirs(date_path, exist_ok=True)
        
        # Decide status
        status = random.choice(["APPROVED", "REJECTED", "NO_SHOW", "EQUIPMENT_FAIL", "CORRUPTED"])
        # Bias towards having around 60-80 approved sessions
        if random.random() < 0.2: 
            status = "APPROVED"
            
        qc_data = {
            "session_id": session["session_id"],
            "status": status,
            "notes": "Generated by system." if status == "APPROVED" else "Fatal error in take."
        }
        
        # Write real QC json
        qc_filename = f"qc_{session['session_id']}_{random.randint(1000,9999)}.json"
        with open(os.path.join(date_path, qc_filename), "w") as f:
            json.dump(qc_data, f)
            
        # Write noise files
        if random.random() < 0.3:
            with open(os.path.join(date_path, f"crash_{session['session_id']}.log"), "w") as f:
                f.write("FATAL EXCEPTION: MEMORY LEAK IN AUDIO BUFFER\\n" * 10)
        
    # 3. Generate Invoices (YAML format, with noise and backups)
    for session in sessions:
        # Even rejected sessions might have invoices, but agent must only sum APPROVED ones
        hours = round(random.uniform(1.0, 8.5), 1)
        invoice_data = {
            "invoice_id": f"INV-{random.randint(10000,99999)}",
            "session_id": session["session_id"],
            "billed_hours": hours,
            "rate": 150.00
        }
        
        # Randomize filename heavily so they can't just guess "invoice_SES-001.yaml" easily
        inv_filename = f"billing_record_{hashlib.md5(session['session_id'].encode()).hexdigest()[:8]}.yaml"
        with open(os.path.join("finance/invoices", inv_filename), "w") as f:
            yaml.dump(invoice_data, f)
            
        # Add noise files in finance
        if random.random() < 0.1:
            with open(os.path.join("finance/invoices", f"{inv_filename}.bak"), "w") as f:
                f.write("BINARY_GARBAGE_IGNORE" + str(random.random()))

    # 4. Generate Audio Archive (Hex nested folders, multiple takes, mp3s)
    instruments = ["vocals", "drums", "bass", "synth", "guitar"]
    for session in sessions:
        # Create hex path
        hex_dir = hashlib.sha1(session["session_id"].encode()).hexdigest()[:4]
        path_p1 = hex_dir[:2]
        path_p2 = hex_dir[2:]
        audio_path = os.path.join("audio_archive", path_p1, path_p2)
        os.makedirs(audio_path, exist_ok=True)
        
        inst = random.choice(instruments)
        
        # Create a final wav (This is the target)
        final_wav = f"{session['session_id']}_{inst}_final.wav"
        with open(os.path.join(audio_path, final_wav), "wb") as f:
            f.write(b"RIFF dummy header... WAV data final.")
            
        # Create noise audio files for the same session
        takes = random.randint(1, 4)
        for t in range(takes):
            take_wav = f"{session['session_id']}_{inst}_take{t+1}.wav"
            with open(os.path.join(audio_path, take_wav), "wb") as f:
                f.write(b"RIFF dummy header... bad take.")
                
        # Create rough mix mp3
        with open(os.path.join(audio_path, f"{session['session_id']}_rough_mix.mp3"), "wb") as f:
            f.write(b"ID3 tag... compressed garbage.")

if __name__ == "__main__":
    build_env()
