import os
import json
import csv
import random
import re

def generate_names(count):
    firsts = ["Sarah", "Michael", "Emily", "David", "Chloe", "Gary", "Melissa", "John", "Jane", "Alice", "Bob", "Charlie", "Diana", "Eve", "Frank", "Grace", "Hank", "Ivy", "Jack", "Karen", "Leo", "Mia", "Nina", "Oscar", "Paul", "Quinn", "Rachel", "Sam", "Tina", "Ursula", "Victor", "Wendy", "Xander", "Yara", "Zane"]
    lasts = ["Jenkins", "Chang", "Davis", "Rodriguez", "Dubois", "Smith", "Vance", "Doe", "Johnson", "Williams", "Brown", "Jones", "Garcia", "Miller", "Martinez", "Taylor", "Anderson", "Thomas", "Jackson", "White", "Harris", "Martin", "Thompson", "Garcia", "Martinez", "Robinson", "Clark", "Rodriguez", "Lewis", "Lee", "Walker", "Hall", "Allen", "Young", "Hernandez"]
    
    names = set()
    while len(names) < count:
        names.add(f"{random.choice(firsts)} {random.choice(lasts)}")
    return list(names)

def build_env():
    random.seed(1878)
    os.makedirs("bg_checks", exist_ok=True)
    os.makedirs("field_reports", exist_ok=True)

    # 1. Generate Background Checks (Fragmented & Noisy)
    all_applicants = generate_names(400)
    approved_volunteers = set()
    
    for i, name in enumerate(all_applicants):
        status = random.choices(["approved", "pending", "rejected"], weights=[0.4, 0.4, 0.2])[0]
        if status == "approved":
            approved_volunteers.add(name)
        
        region = f"region_{random.randint(1, 15)}"
        month = f"2023_{random.randint(1, 12):02d}"
        target_dir = os.path.join("bg_checks", region, month)
        os.makedirs(target_dir, exist_ok=True)
        
        # Noise: Sometimes output as JSON, sometimes YAML-like txt (we stick to JSON to fit script limits but fragment it)
        file_path = os.path.join(target_dir, f"app_{i:04d}.json")
        with open(file_path, "w", encoding="utf-8") as f:
            json.dump({
                "applicant_id": f"ID-{i}",
                "full_name": name,
                "clearance_level": random.randint(1, 5),
                "status": status,
                "notes": "Generated by system"
            }, f, indent=2)

    # 2. Generate Field Reports (Scale, Noise, Decoys, Formatting chaos)
    # We'll use names from all_applicants + some completely unknown names (gatecrashers)
    unknown_names = generate_names(50)
    possible_workers = all_applicants + unknown_names

    def format_time(hours):
        choice = random.randint(1, 4)
        if choice == 1:
            return f"{hours} hrs"
        elif choice == 2:
            return f"{hours}"
        elif choice == 3:
            return f"{int(hours * 60)} mins"
        else:
            return f"{int(hours * 60)} minutes"

    for i in range(200):
        # Determine if this file is valid or noise
        is_final = random.choice([True, False])
        is_bak = random.choice([True, False])
        prefix = "FINAL_" if is_final else random.choice(["DRAFT_", "TEMP_", "LOG_"])
        suffix = ".bak" if is_bak else ""
        ext = random.choice([".json", ".csv", ".txt"])
        
        filename = f"{prefix}site_{random.randint(1,50)}_{i:03d}{ext}{suffix}"
        filepath = os.path.join("field_reports", filename)
        
        # Select some workers
        workers = random.sample(possible_workers, random.randint(3, 10))
        data = []
        for w in workers:
            hours = round(random.uniform(1.0, 5.0) * 2) / 2 # increments of 0.5
            data.append((w, hours))

        if ext == ".json":
            json_data = [{"v_name": w, "duration": format_time(h)} for w, h in data]
            with open(filepath, "w", encoding="utf-8") as f:
                json.dump(json_data, f, indent=2)
                
        elif ext == ".csv":
            with open(filepath, "w", newline="", encoding="utf-8") as f:
                writer = csv.writer(f)
                writer.writerow(["Volunteer Name", "Time Logged"])
                for w, h in data:
                    writer.writerow([w, format_time(h)])
                    
        elif ext == ".txt":
            with open(filepath, "w", encoding="utf-8") as f:
                for w, h in data:
                    f.write(f"Name: {w} | Time: {format_time(h)}\n")

if __name__ == "__main__":
    build_env()
