import os
import json
import hashlib

def verify():
    base_dir = "."
    result = {
        "palette_created": False,
        "palette_correct": False,
        "script_fixed_and_run": False,
        "canvas_bin_correct": False,
        "vip_list_created": False,
        "vip_list_correct": False
    }

    # 1. Check palette.json
    palette_path = os.path.join(base_dir, "palette.json")
    expected_hex = {"#FF6432", "#0A141E", "#228B22"} # upper or lower is fine, will check case insensitive
    
    actual_palette = []
    if os.path.exists(palette_path):
        result["palette_created"] = True
        try:
            with open(palette_path, 'r') as f:
                actual_palette = json.load(f)
            if isinstance(actual_palette, list):
                actual_hex_set = {h.upper() for h in actual_palette}
                if actual_hex_set == expected_hex:
                    result["palette_correct"] = True
        except:
            pass

    # 2. Check canvas.bin
    canvas_path = os.path.join(base_dir, "canvas.bin")
    if os.path.exists(canvas_path):
        result["script_fixed_and_run"] = True
        try:
            with open(canvas_path, 'r') as f:
                content = f.read().strip()
            
            # Reconstruct expected hash based on the actual palette generated by agent (if it's valid JSON list)
            if result["palette_correct"]:
                json_str = json.dumps(actual_palette, separators=(',', ':'))
                expected_hash = hashlib.md5(json_str.encode('utf-8')).hexdigest()
                expected_content = "SMARTCANVAS_" + expected_hash
                if content == expected_content:
                    result["canvas_bin_correct"] = True
        except:
            pass

    # 3. Check vip_list.txt
    vip_path = os.path.join(base_dir, "vip_list.txt")
    expected_emails = {"curator@gallery-az.com", "john.doe@scottsdale.art", "boss@phoenix.art", "info@gallery-az.com"}
    
    if os.path.exists(vip_path):
        result["vip_list_created"] = True
        try:
            with open(vip_path, 'r') as f:
                lines = f.readlines()
            actual_emails = {line.strip() for line in lines if line.strip()}
            if actual_emails == expected_emails:
                result["vip_list_correct"] = True
        except:
            pass

    # Save verification state
    with open(os.path.join(base_dir, "verify_result.json"), "w") as f:
        json.dump(result, f, indent=4)

if __name__ == "__main__":
    verify()
