import os
import csv
import json
import random
from datetime import datetime, timedelta

def build_env():
    # 🚨 Ensure deterministic generation for testing
    random.seed(42)

    # 1. Create Base Directories
    os.makedirs("legal_dept/contracts", exist_ok=True)
    os.makedirs("finance_ops", exist_ok=True)
    os.makedirs("server_dumps/ad_ops", exist_ok=True)

    # 2. Setup Platform Factors (Finance)
    platforms = {
        "TikTok": 1.5,
        "Instagram": 1.2,
        "X_Twitter": 1.0,
        "Meta_VR": 2.5,
        "Underground_BBS": 0.8
    }
    with open("finance_ops/platform_factors.csv", "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["platform_name", "multiplier_factor"])
        for p, m in platforms.items():
            writer.writerow([p, m])

    # 3. Generate Influencers & Legal Contracts
    valid_influencers = {}
    
    # Generate 150 contracts. Only about 40 will be fully valid.
    for i in range(1, 151):
        handle = f"@user_{random.randint(1000, 9999)}_x"
        base_rate = random.choice([100, 150, 200, 250, 300, 500])
        
        is_signed = random.choice([True, False, True])
        is_cleared = random.choice([True, False])
        
        status = "SIGNED" if is_signed else random.choice(["DRAFT", "EXPIRED", "TERMINATED"])
        
        contract_data = {
            "influencer_handle": handle,
            "base_rate": base_rate,
            "contract_status": status,
            "compliance_cleared": is_cleared,
            "notes": "Generated by LegalBot."
        }
        
        if status == "SIGNED" and is_cleared:
            valid_influencers[handle] = base_rate
            
        with open(f"legal_dept/contracts/contract_{i:03d}.json", "w") as f:
            json.dump(contract_data, f, indent=2)

    valid_handles = list(valid_influencers.keys())
    
    # Generate some strictly invalid handles that will appear in logs
    invalid_handles = [f"@intruder_{random.randint(1000,9999)}_z" for _ in range(80)]
    all_handles_pool = valid_handles + invalid_handles

    # 4. Generate Campaign Logs across 30 days
    start_date = datetime(2024, 1, 1)
    for day_offset in range(30):
        current_date = start_date + timedelta(days=day_offset)
        date_str = current_date.strftime("%Y/%m/%d")
        daily_path = os.path.join("server_dumps/ad_ops", date_str)
        os.makedirs(daily_path, exist_ok=True)
        
        # Format 1: CSV
        csv_platform = random.choice(list(platforms.keys()))
        with open(os.path.join(daily_path, f"{csv_platform}_records.csv"), "w", newline="") as f:
            writer = csv.writer(f)
            writer.writerow(["influencer_handle", "action_status", "post_count"])
            for _ in range(random.randint(10, 25)):
                h = random.choice(all_handles_pool)
                status = random.choice(["published", "published", "draft", "rejected"])
                writer.writerow([h, status, random.randint(1, 5)])

        # Format 2: JSON
        json_platform = random.choice(list(platforms.keys()))
        json_data = {
            "metadata": {
                "export_date": date_str,
                "platform": json_platform
            },
            "data_payload": []
        }
        for _ in range(random.randint(10, 25)):
            h = random.choice(all_handles_pool)
            status = random.choice(["published", "published", "draft", "rejected"])
            json_data["data_payload"].append({
                "user": h,
                "state": status,
                "qty": random.randint(1, 5)
            })
        with open(os.path.join(daily_path, f"export_{json_platform.lower()}.json"), "w") as f:
            json.dump(json_data, f, indent=2)

        # Format 3: TXT (Pipe separated)
        txt_platform = random.choice(list(platforms.keys()))
        with open(os.path.join(daily_path, "raw_dump.txt"), "w") as f:
            f.write(f"PLATFORM: {txt_platform}\n")
            f.write("handle|status|count\n")
            for _ in range(random.randint(10, 25)):
                h = random.choice(all_handles_pool)
                status = random.choice(["published", "published", "draft", "rejected"])
                f.write(f"{h}|{status}|{random.randint(1, 5)}\n")

    # (Self-Verification / Ground Truth Calculation Logic embedded as comments)
    # total_spend = 0.0
    # intruders = set()
    # (Agent must write code to correctly parse all three file formats, 
    # check valid_influencers dict, and apply the correct math.)

if __name__ == "__main__":
    build_env()
