import os
import json
import httpx
from openai import OpenAI

# 必须约定这三个环境变量
MOCK_API_KEY = os.environ.get("MOCK_API_KEY", "dummy_key")
MOCK_API_BASE = os.environ.get("MOCK_API_BASE", "http://localhost/v1")
MOCK_MODEL_NAME = os.environ.get("MOCK_MODEL_NAME", "gpt-5.4")

# 必须使用 httpx 关闭 SSL 验证，防止评测环境证书问题
http_client = httpx.Client(verify=False)

try:
    client = OpenAI(
        api_key=MOCK_API_KEY,
        base_url=MOCK_API_BASE,
        http_client=http_client
    )
except Exception:
    client = None

def engine_ops_ai_skill(user_query: str) -> str:
    """
    LLM-as-a-Mock: Simulates an AI assistant that analyzes cloud memory dumps.
    It reads the hidden ground truth file to accurately ground its responses.
    """
    if not user_query:
        return "Error: Missing query parameter."
        
    # Read the hidden ground truth generated by env_builder
    ground_truth_path = "mem_dumps/.hidden_mem_map.json"
    if not os.path.exists(ground_truth_path):
        return "System Error: The cloud analyzer cannot locate the snapshot index. Was the environment built correctly?"
        
    try:
        with open(ground_truth_path, "r", encoding="utf-8") as f:
            truth_data = json.load(f)
    except Exception as e:
        return f"System Error: Failed to read hidden map: {str(e)}"
        
    # Construct facts for the LLM to ground its hallucination
    system_prompt = (
        "你是一个专业的游戏引擎云端内存诊断 AI (EngineOps AI)。"
        "你刚刚扫描了一个 8.4GB 的内存竞技场快照文件。以下是绝对真实的内部检索结果（Ground Truth），请利用这些结果回答用户：\n"
        f"- ARCH_1A_STATIC_COLLIDER 的最高碎片化内存段首地址是：{truth_data['ARCH_1A_STATIC_COLLIDER']['highest_frag_address']} (碎片数: {truth_data['ARCH_1A_STATIC_COLLIDER']['frag_count']})。\n"
        f"- ARCH_E7_DYNAMIC_MESH 的最高碎片化内存段首地址是：{truth_data['ARCH_E7_DYNAMIC_MESH']['highest_frag_address']} (碎片数: {truth_data['ARCH_E7_DYNAMIC_MESH']['frag_count']})。这是全场最灾难的内存段。\n"
        f"- 其它 Archetype 的碎片化地址基本都在 {truth_data['default_frag_address']} 附近徘徊。\n"
        "请注意，用户可能不知道具体的地址，他们会向你询问。你的回答应当像一个真正的技术助手，直接告诉他们查询的 Archetype 对应的内存地址（SEG_HEAD）是多少，语言要专业且简练。"
    )
    
    if not client:
        return "System Error: OpenAI client initialization failed. Check environment variables."

    try:
        response = client.chat.completions.create(
            model=MOCK_MODEL_NAME,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": f"User Query: {user_query}"}
            ],
            temperature=0.1 # Low temp to ensure strict extraction of the address
        )
        return response.choices[0].message.content
    except Exception as e:
        return f"EngineOps AI Service Error: Connection failed. {str(e)}"
