import os
import argparse
import csv

def create_hexdump(data: bytearray) -> str:
    """生成类似 hexdump -C 的字符串输出"""
    lines = []
    for i in range(0, len(data), 16):
        chunk = data[i:i+16]
        hex_part = ' '.join(f'{b:02x}' for b in chunk)
        # ascii representation
        ascii_part = ''.join(chr(b) if 32 <= b <= 126 else '.' for b in chunk)
        lines.append(f'{i:08x}  {hex_part:<47}  |{ascii_part}|')
    return '\n'.join(lines)

def build_turn_1():
    os.makedirs("dumps", exist_ok=True)
    os.makedirs("docs", exist_ok=True)
    os.makedirs("recovery_workspace", exist_ok=True)

    # 1. 规范文档
    spec_content = """=== INTERNAL EXT4 MOCK SPECIFICATION ===
Structure Offsets (Little Endian):
1. Superblock (Size: 1024 bytes)
   - 0x038 : Magic Signature (2 bytes, expecting 0x53 0xEF)
   - 0x0E8 : s_last_orphan (4 bytes) -> Points to the first Inode in the orphan chain.

2. Inode Structure (Size: 256 bytes)
   - 0x07C : i_orphan (4 bytes) -> Points to the next Inode in the orphan chain. 0x00000000 means end of list.
========================================
"""
    with open("docs/mock_ext4_spec.txt", "w", encoding="utf-8") as f:
        f.write(spec_content)

    # 2. dmesg 模拟日志 (包含中止TID: 88492, 和坏道: 0x7B99A0)
    dmesg_content = """[ 1234.5012] EXT4-fs (nvme0n1): mounted filesystem with ordered data mode. Opts: (null)
[ 1482.1123] nvme nvme0: controller is down; will reset: CSTS=0xffffffff, PCI_STATUS=0xffff
[ 1482.1129] EXT4-fs warning (device nvme0n1): ext4_end_bio:348: I/O error 10 writing to inode 101 (offset 0 size 4096 starting block 12903)
[ 1482.1140] blk_update_request: critical medium error, dev nvme0n1, sector 0x7B99A0 op 0x0:(READ)
[ 1482.1155] Aborting journal on device nvme0n1-8.
[ 1482.1160] EXT4-fs (nvme0n1): ext4_journal_check_start: Journal transaction 88492 aborted.
[ 1482.1188] Kernel panic - not syncing: EXT4-fs panic from previous errors.
"""
    with open("dumps/dmesg.log", "w", encoding="utf-8") as f:
        f.write(dmesg_content)

    # 3. 构造 Superblock (Head -> 101)
    sb = bytearray(1024)
    sb[0x38:0x3A] = b'\x53\xEF'
    sb[0xE8:0xEC] = (101).to_bytes(4, 'little')
    with open("dumps/superblock.txt", "w", encoding="utf-8") as f:
        f.write(create_hexdump(sb))

    # 4. 构造 Inodes
    # Inode 101 -> 102
    i101 = bytearray(256)
    i101[0x7C:0x80] = (102).to_bytes(4, 'little')
    with open("dumps/inode_101.txt", "w", encoding="utf-8") as f:
        f.write(create_hexdump(i101))

    # Inode 102 -> 104
    i102 = bytearray(256)
    i102[0x7C:0x80] = (104).to_bytes(4, 'little')
    with open("dumps/inode_102.txt", "w", encoding="utf-8") as f:
        f.write(create_hexdump(i102))

    # Inode 103 -> 0 (Distractor, not in chain)
    i103 = bytearray(256)
    i103[0x7C:0x80] = (0).to_bytes(4, 'little')
    with open("dumps/inode_103.txt", "w", encoding="utf-8") as f:
        f.write(create_hexdump(i103))

    # Inode 104 -> 0 (End of chain)
    i104 = bytearray(256)
    i104[0x7C:0x80] = (0).to_bytes(4, 'little')
    with open("dumps/inode_104.txt", "w", encoding="utf-8") as f:
        f.write(create_hexdump(i104))

    # Inode 105 -> 0 (Distractor)
    i105 = bytearray(256)
    i105[0x7C:0x80] = (0).to_bytes(4, 'little')
    with open("dumps/inode_105.txt", "w", encoding="utf-8") as f:
        f.write(create_hexdump(i105))


def build_turn_2():
    # 模拟时间流逝，添加 CSV 日志记录
    # 中止 TID = 88492
    # 孤儿链: 101, 102, 104
    csv_data = [
        ["Record_ID", "TID", "Inode_Ref", "Data_Hash"],
        ["R001", "88490", "101", "ABC1"], # <= 88492, 不可挽救
        ["R002", "88493", "101", "DEF2"], # > 88492, 可挽救
        ["R003", "88495", "103", "AAA1"], # 干扰项，不在链中
        ["R004", "88491", "104", "BBB2"], # <= 88492, 不可挽救
        ["R005", "88494", "102", "CCC3"], # > 88492, 可挽救
        ["R006", "88499", "105", "DDD4"], # 干扰项
    ]
    
    with open("dumps/journal_records.csv", "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerows(csv_data)


def build_turn_3():
    os.makedirs("tools", exist_ok=True)
    template_content = """#!/bin/bash
# AUTOGENERATED RESCUE SCRIPT
# DO NOT MODIFY MANUALLY

echo "Initializing Ext4 advanced rescue protocol..."

/usr/local/sbin/ext4_rescue_tool --device /dev/nvme0n1 \\
    --skip-sector {{BAD_SECTOR}} \\
    {{RECOVER_FLAGS}} \\
    {{CLEAR_FLAGS}}

if [ $? -eq 0 ]; then
    echo "Rescue completed successfully!"
else
    echo "Rescue failed with critical error."
    exit 1
fi
"""
    with open("tools/rescue_template.sh", "w", encoding="utf-8") as f:
        f.write(template_content)

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--turn", type=int, required=True)
    args = parser.parse_args()
    
    if args.turn == 1:
        build_turn_1()
    elif args.turn == 2:
        build_turn_2()
    elif args.turn == 3:
        build_turn_3()
